name = "elizoscog-workers-for-platforms-test"
main = "src/minimal-worker.ts"
compatibility_date = "2024-04-03"

[[ dispatch_namespaces ]]
binding = "dispatcher"
namespace = "elizoscog-workers-for-platforms" # make sure this is the same as the DISPATCH_NAMESPACE_NAME var

[[ d1_databases ]]
binding = "DB"
database_name = "elizoscog-workers-for-platforms"
database_id = "00000000-0000-0000-0000-000000000000"
preview_database_id = "00000000-0000-0000-0000-000000000000"

[vars]
DISPATCH_NAMESPACE_NAME = "elizoscog-workers-for-platforms"
DISPATCH_NAMESPACE_ACCOUNT_ID = "replace_with_your_account_id"
# The necessary secrets are:
# - DISPATCH_NAMESPACE_API_TOKEN
# Run `echo <VALUE> | wrangler secret put <SECRET_NAME>` for each of these